In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from autofeat import FeatureSelector, AutoFeatRegressor

import matplotlib.pyplot as plt

In [25]:
dfcall=pd.read_csv('/Users/nihaalnadaf/Downloads/equity/DF_call.csv')
dfput=pd.read_csv('/Users/nihaalnadaf/Downloads/equity/DF_put.csv')

In [27]:
dfcall.isnull().sum() , dfputt.isnull().sum()

(Unnamed: 0              0
 STOCK_PRICE             0
 STOCK_VOLUME            0
 vwap                    0
 Date                    0
 STRIKE_PR               0
 OPTION_TYP              0
 OPEN                    0
 HIGH                    0
 LOW                     0
 CLOSE                   0
 SETTLE_PR               0
 CONTRACTS               0
 OPEN_INT                0
 CHG_IN_OI               0
 exp_date                0
 time_to_expiry_years    0
 Delta                   0
 Gamma                   0
 Vega                    0
 Theta                   0
 Rho                     0
 dtype: int64,
 STOCK_PRICE             0
 STOCK_VOLUME            0
 vwap                    0
 STRIKE_PR               0
 OPEN                    0
 HIGH                    0
 LOW                     0
 CLOSE                   0
 SETTLE_PR               0
 CONTRACTS               0
 OPEN_INT                0
 CHG_IN_OI               0
 time_to_expiry_years    0
 Delta                   0
 Gamma                   0
 Vega                    0
 Theta                   0
 Rho                     0
 dtype: int64)

In [29]:
dfcall.head(5)

,Unnamed: 0,STOCK_PRICE,STOCK_VOLUME,vwap,Date,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,...,CONTRACTS,OPEN_INT,CHG_IN_OI,exp_date,time_to_expiry_years,Delta,Gamma,Vega,Theta,Rho
0,112,1051.2,3328572,1051.3,2010-12-30,500.0,CE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,1.0,8.558025e-58,1.233271e-55,-0.088598,0.381654
1,113,1051.2,3328572,1051.3,2010-12-30,550.0,CE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,1.0,1.072084e-44,1.544947e-42,-0.097458,0.419819
2,114,1051.2,3328572,1051.3,2010-12-30,580.0,CE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,1.0,3.603227e-38,5.192499e-36,-0.102774,0.442718
3,115,1051.2,3328572,1051.3,2010-12-30,600.0,CE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,1.0,2.715170e-34,3.912748e-32,-0.106318,0.457985
4,116,1051.2,3328572,1051.3,2010-12-30,620.0,CE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,1.0,9.323324e-31,1.343555e-28,-0.109862,0.473251

In [31]:
dfcall=dfcall.drop(columns=['Unnamed: 0','OPTION_TYP','Date','exp_date'])

In [33]:
dfcall=dfcall.drop(dfcall[dfcall['SETTLE_PR'] < 0.01].index)

In [37]:
dfput.head()

,Unnamed: 0,STOCK_PRICE,STOCK_VOLUME,vwap,Date,STRIKE_PR,OPTION_TYP,OPEN,HIGH,LOW,...,CONTRACTS,OPEN_INT,CHG_IN_OI,exp_date,time_to_expiry_years,Delta,Gamma,Vega,Theta,Rho
0,168,1051.2,3328572,1051.3,2010-12-30,500.0,PE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,0.0,8.558025e-58,1.233271e-55,-3.694069e-56,-2.144706e-57
1,169,1051.2,3328572,1051.3,2010-12-30,550.0,PE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,0.0,1.072084e-44,1.544947e-42,-4.618612e-43,-3.075931e-44
2,170,1051.2,3328572,1051.3,2010-12-30,580.0,PE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,0.0,3.603227e-38,5.192499e-36,-1.550190e-36,-1.124481e-37
3,171,1051.2,3328572,1051.3,2010-12-30,600.0,PE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,0.0,2.715170e-34,3.912748e-32,-1.166963e-32,-8.975493e-34
4,172,1051.2,3328572,1051.3,2010-12-30,620.0,PE,0.0,0.0,0.0,...,0.0,0.0,0.0,2011-01-27,0.076712,0.0,9.323324e-31,1.343555e-28,-4.002758e-29,-3.269220e-30

In [50]:
dfcall.columns

Index(['STOCK_PRICE', 'STOCK_VOLUME', 'vwap ', 'STRIKE_PR', 'OPEN', 'HIGH',
       'LOW', 'CLOSE', 'SETTLE_PR', 'CONTRACTS', 'OPEN_INT', 'CHG_IN_OI',
       'time_to_expiry_years', 'Delta', 'Gamma', 'Vega', 'Theta', 'Rho'],
      dtype='object')

In [39]:
dfput=dfput.drop(columns=['Unnamed: 0','OPTION_TYP','Date','exp_date'])

In [41]:
dfput=dfput.drop(dfput[dfput['SETTLE_PR'] < 0.01].index)

In [47]:
dfput['STOCK_PRICE'].count(),dfcall['STOCK_PRICE'].count()

(381038, 402365)

### Feature Engineering

In [54]:
X=dfcall.drop('SETTLE_PR', axis=1)
y=dfcall['SETTLE_PR']
afreg = AutoFeatRegressor(verbose=1, feateng_steps=1)
X_new = afreg.fit_transform(X, y)
print('New features: ', afreg.new_feat_cols_)

2025-01-20 12:43:35,629 INFO: [AutoFeat] The 1 step feature engineering process could generate up to 119 features.
2025-01-20 12:43:35,631 INFO: [AutoFeat] With 402365 data points this new feature matrix would use about 0.19 gb of space.
2025-01-20 12:43:35,670 INFO: [feateng] Step 1: transformation of original features

2025-01-20 12:43:37,116 INFO: [feateng] Generated 57 transformed features from 17 original features - done.
2025-01-20 12:43:37,273 INFO: [feateng] Generated altogether 70 new features in 1 steps
2025-01-20 12:43:37,274 INFO: [feateng] Removing correlated features, as well as additions at the highest level
2025-01-20 12:43:37,426 INFO: [feateng] Generated a total of 33 additional features

[featsel] Scaling data...

2025-01-20 12:43:38,562 INFO: [featsel] Feature selection run 1/5

done.

2025-01-20 12:43:56,250 INFO: [featsel] Feature selection run 2/5
2025-01-20 12:44:10,125 INFO: [featsel] Feature selection run 3/5
2025-01-20 12:44:24,860 INFO: [featsel] Feature selection run 4/5
2025-01-20 12:44:41,562 INFO: [featsel] Feature selection run 5/5
2025-01-20 12:44:54,195 INFO: [featsel] 37 features after 5 feature selection runs
/opt/anaconda3/lib/python3.12/site-packages/autofeat/featsel.py:270: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  if np.max(np.abs(correlations[c].ravel()[:i])) < 0.9:
2025-01-20 12:44:56,822 INFO: [featsel] 27 features after correlation filtering
2025-01-20 12:44:59,627 INFO: [featsel] 26 features after noise filtering
2025-01-20 12:44:59,636 INFO: [AutoFeat] Computing 14 new features.

2025-01-20 12:45:00,309 INFO: [AutoFeat]    14/   14 new features ...done.
2025-01-20 12:45:00,331 INFO: [AutoFeat] Final dataframe with 31 feature columns (14 new).
2025-01-20 12:45:00,332 INFO: [AutoFeat] Training final regression model.

2025-01-20 12:45:01,737 INFO: [AutoFeat] Trained model: largest coefficients:
2025-01-20 12:45:01,737 INFO: -337.56366438421776
2025-01-20 12:45:01,739 INFO: -400629.781891 * Gamma**2
2025-01-20 12:45:01,739 INFO: 23322.659218 * Gamma
2025-01-20 12:45:01,740 INFO: 979.160975 * Theta
2025-01-20 12:45:01,741 INFO: 492.900662 * Theta**2
2025-01-20 12:45:01,741 INFO: -473.023791 * time_to_expiry_years
2025-01-20 12:45:01,742 INFO: 306.393208 * Delta
2025-01-20 12:45:01,742 INFO: 71.427388 * Theta**3
2025-01-20 12:45:01,743 INFO: 61.668762 * Vega
2025-01-20 12:45:01,743 INFO: 52.356482 * 1/CLOSE
2025-01-20 12:45:01,744 INFO: 11.586506 * log(CLOSE)
2025-01-20 12:45:01,744 INFO: 11.070207 * log(STOCK_VOLUME)
2025-01-20 12:45:01,745 INFO: 4.228335 * sqrt(CONTRACTS)
2025-01-20 12:45:01,745 INFO: 0.918969 * Rho**3
2025-01-20 12:45:01,746 INFO: 0.742528 * CLOSE
2025-01-20 12:45:01,746 INFO: -0.474075 * exp(Vega)
2025-01-20 12:45:01,747 INFO: -0.231946 * sqrt(OPEN_INT)
2025-01-20 12:45:01,747 INFO: 0.121167 * LOW
2025-01-20 12:45:01,748 INFO: 0.100527 * STRIKE_PR
2025-01-20 12:45:01,748 INFO: -0.017807 * CONTRACTS
2025-01-20 12:45:01,749 INFO: 0.000210 * Abs(CHG_IN_OI)
2025-01-20 12:45:01,749 INFO: -0.000145 * CHG_IN_OI
2025-01-20 12:45:01,750 INFO: 0.000059 * OPEN_INT
2025-01-20 12:45:01,750 INFO: 0.000051 * LOW**2
2025-01-20 12:45:01,764 INFO: [AutoFeat] Final score: 0.5370

New features:  ['Rho**3', 'LOW**2', '1/CLOSE', 'Theta**2', 'Gamma**2', 'CLOSE**3', 'Theta**3', 'exp(Vega)', 'log(CLOSE)', 'sqrt(OPEN_INT)', 'Abs(CHG_IN_OI)', 'sqrt(CONTRACTS)', 'log(STOCK_VOLUME)', 'CONTRACTS**2']

In [58]:
X_new.head()

,STOCK_PRICE,STOCK_VOLUME,vwap,STRIKE_PR,OPEN,HIGH,LOW,CLOSE,CONTRACTS,OPEN_INT,...,Gamma**2,CLOSE**3,Theta**3,exp(Vega),log(CLOSE),sqrt(OPEN_INT),Abs(CHG_IN_OI),sqrt(CONTRACTS),log(STOCK_VOLUME),CONTRACTS**2
0,1051.2,3328572.0,1051.3,500.0,0.0,0.0,0.0,591.70,0.0,0.0,...,7.323980e-115,2.071594e+08,-0.000695,1.0,6.383000,0.0,0.0,0.0,15.018054,0.0
1,1051.2,3328572.0,1051.3,550.0,0.0,0.0,0.0,542.65,0.0,0.0,...,1.149364e-88,1.597936e+08,-0.000926,1.0,6.296465,0.0,0.0,0.0,15.018054,0.0
2,1051.2,3328572.0,1051.3,580.0,0.0,0.0,0.0,407.65,0.0,0.0,...,1.298324e-75,6.774267e+07,-0.001086,1.0,6.010409,0.0,0.0,0.0,15.018054,0.0
3,1051.2,3328572.0,1051.3,600.0,0.0,0.0,0.0,493.60,0.0,0.0,...,7.372151e-68,1.202612e+08,-0.001202,1.0,6.201725,0.0,0.0,0.0,15.018054,0.0
4,1051.2,3328572.0,1051.3,620.0,0.0,0.0,0.0,385.40,0.0,0.0,...,8.692438e-61,5.724468e+07,-0.001326,1.0,5.954282,0.0,0.0,0.0,15.018054,0.0

In [66]:
X_new.columns

Index(['STOCK_PRICE', 'STOCK_VOLUME', 'vwap ', 'STRIKE_PR', 'OPEN', 'HIGH',
       'LOW', 'CLOSE', 'CONTRACTS', 'OPEN_INT', 'CHG_IN_OI',
       'time_to_expiry_years', 'Delta', 'Gamma', 'Vega', 'Theta', 'Rho',
       'Rho**3', 'LOW**2', '1/CLOSE', 'Theta**2', 'Gamma**2', 'CLOSE**3',
       'Theta**3', 'exp(Vega)', 'log(CLOSE)', 'sqrt(OPEN_INT)',
       'Abs(CHG_IN_OI)', 'sqrt(CONTRACTS)', 'log(STOCK_VOLUME)',
       'CONTRACTS**2'],
      dtype='object')

In [70]:
path='/Users/nihaalnadaf/Downloads/equity/'
X_new.to_csv(path + 'calls_data.csv', index=False)
y.to_csv(path + 'calls_target.csv', index=False)

### Repeating Feature Engineering for Puts

In [73]:
X=dfput.drop('SETTLE_PR', axis=1)
y=dfput['SETTLE_PR']
afreg = AutoFeatRegressor(verbose=1, feateng_steps=1)
X_new = afreg.fit_transform(X, y)
print('New features: ', afreg.new_feat_cols_)

2025-01-20 12:52:48,534 INFO: [AutoFeat] The 1 step feature engineering process could generate up to 119 features.
2025-01-20 12:52:48,534 INFO: [AutoFeat] With 381038 data points this new feature matrix would use about 0.18 gb of space.
2025-01-20 12:52:48,561 INFO: [feateng] Step 1: transformation of original features

2025-01-20 12:52:49,461 INFO: [feateng] Generated 57 transformed features from 17 original features - done.
2025-01-20 12:52:49,602 INFO: [feateng] Generated altogether 68 new features in 1 steps
2025-01-20 12:52:49,602 INFO: [feateng] Removing correlated features, as well as additions at the highest level
2025-01-20 12:52:49,754 INFO: [feateng] Generated a total of 32 additional features
2025-01-20 12:52:49,899 INFO: [featsel] Feature selection run 1/5

[featsel] Scaling data...done.

2025-01-20 12:53:04,809 INFO: [featsel] Feature selection run 2/5
2025-01-20 12:53:18,359 INFO: [featsel] Feature selection run 3/5
2025-01-20 12:53:31,571 INFO: [featsel] Feature selection run 4/5
2025-01-20 12:53:44,384 INFO: [featsel] Feature selection run 5/5
2025-01-20 12:53:56,626 INFO: [featsel] 38 features after 5 feature selection runs
/opt/anaconda3/lib/python3.12/site-packages/autofeat/featsel.py:270: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  if np.max(np.abs(correlations[c].ravel()[:i])) < 0.9:
2025-01-20 12:53:59,392 INFO: [featsel] 27 features after correlation filtering
2025-01-20 12:54:01,990 INFO: [featsel] 25 features after noise filtering
2025-01-20 12:54:01,992 INFO: [AutoFeat] Computing 13 new features.

2025-01-20 12:54:02,562 INFO: [AutoFeat]    13/   13 new features ...done.
2025-01-20 12:54:02,581 INFO: [AutoFeat] Final dataframe with 30 feature columns (13 new).
2025-01-20 12:54:02,582 INFO: [AutoFeat] Training final regression model.

2025-01-20 12:54:03,504 INFO: [AutoFeat] Trained model: largest coefficients:
2025-01-20 12:54:03,505 INFO: -539.4037247652769
2025-01-20 12:54:03,506 INFO: -1610.158499 * Gamma
2025-01-20 12:54:03,506 INFO: -262.075155 * Delta
2025-01-20 12:54:03,507 INFO: -157.460973 * Abs(Theta)
2025-01-20 12:54:03,508 INFO: 152.313283 * exp(Rho)
2025-01-20 12:54:03,508 INFO: -146.941671 * time_to_expiry_years
2025-01-20 12:54:03,509 INFO: -126.960639 * Theta
2025-01-20 12:54:03,509 INFO: 32.775113 * 1/CLOSE
2025-01-20 12:54:03,510 INFO: -32.246084 * Vega
2025-01-20 12:54:03,510 INFO: -20.046015 * Rho
2025-01-20 12:54:03,511 INFO: -19.467499 * Theta**2
2025-01-20 12:54:03,511 INFO: 18.048260 * log(STOCK_VOLUME)
2025-01-20 12:54:03,512 INFO: 9.471449 * log(CLOSE)
2025-01-20 12:54:03,512 INFO: 1.129285 * sqrt(CONTRACTS)
2025-01-20 12:54:03,513 INFO: 0.848204 * Vega**3
2025-01-20 12:54:03,513 INFO: 0.565442 * CLOSE
2025-01-20 12:54:03,514 INFO: -0.482178 * LOW
2025-01-20 12:54:03,515 INFO: 0.065344 * vwap
2025-01-20 12:54:03,515 INFO: -0.052542 * Rho**3
2025-01-20 12:54:03,516 INFO: -0.006530 * CONTRACTS
2025-01-20 12:54:03,516 INFO: 0.001636 * LOW**2
2025-01-20 12:54:03,517 INFO: 0.000826 * Abs(CHG_IN_OI)
2025-01-20 12:54:03,518 INFO: -0.000611 * CHG_IN_OI
2025-01-20 12:54:03,518 INFO: -0.000126 * OPEN_INT
2025-01-20 12:54:03,532 INFO: [AutoFeat] Final score: 0.4164

New features:  ['Rho**3', 'LOW**2', '1/CLOSE', 'Vega**3', 'exp(Rho)', 'Theta**2', 'Gamma**2', 'CLOSE**3', 'Abs(Theta)', 'log(CLOSE)', 'Abs(CHG_IN_OI)', 'sqrt(CONTRACTS)', 'log(STOCK_VOLUME)']

In [75]:
X_new.columns

Index(['STOCK_PRICE', 'STOCK_VOLUME', 'vwap ', 'STRIKE_PR', 'OPEN', 'HIGH',
       'LOW', 'CLOSE', 'CONTRACTS', 'OPEN_INT', 'CHG_IN_OI',
       'time_to_expiry_years', 'Delta', 'Gamma', 'Vega', 'Theta', 'Rho',
       'Rho**3', 'LOW**2', '1/CLOSE', 'Vega**3', 'exp(Rho)', 'Theta**2',
       'Gamma**2', 'CLOSE**3', 'Abs(Theta)', 'log(CLOSE)', 'Abs(CHG_IN_OI)',
       'sqrt(CONTRACTS)', 'log(STOCK_VOLUME)'],
      dtype='object')

In [77]:
X_new.to_csv(path + 'puts_data.csv', index=False)
y.to_csv(path + 'puts_target.csv', index=False)

In [79]:
X_new

,STOCK_PRICE,STOCK_VOLUME,vwap,STRIKE_PR,OPEN,HIGH,LOW,CLOSE,CONTRACTS,OPEN_INT,...,Vega**3,exp(Rho),Theta**2,Gamma**2,CLOSE**3,Abs(Theta),log(CLOSE),Abs(CHG_IN_OI),sqrt(CONTRACTS),log(STOCK_VOLUME)
0,1051.20,3328572.0,1051.3,820.0,0.0,0.0,0.0,2.80,0.0,2500.0,...,1.466212e-19,1.000000,2.370014e-14,1.338941e-17,2.195200e+01,1.539485e-07,1.029619,0.0,0.0,15.018054
1,1051.20,3328572.0,1051.3,840.0,0.0,0.0,0.0,4.85,0.0,0.0,...,3.975655e-16,1.000000,4.572473e-12,2.603572e-15,1.140841e+02,2.138334e-06,1.578979,0.0,0.0,15.018054
2,1051.20,3328572.0,1051.3,850.0,0.0,0.0,0.0,0.95,0.0,0.0,...,1.447201e-14,0.999999,4.999992e-11,2.859672e-14,8.573750e-01,7.071062e-06,-0.051293,0.0,0.0,15.018054
3,1051.20,3328572.0,1051.3,860.0,0.0,0.0,0.0,7.10,0.0,0.0,...,4.192959e-13,0.999995,4.693812e-10,2.697600e-13,3.579110e+02,2.166521e-05,1.960095,0.0,0.0,15.018054
4,1051.20,3328572.0,1051.3,880.0,0.0,0.0,0.0,10.00,0.0,0.0,...,1.827572e-10,0.999962,2.668421e-08,1.550768e-11,1.000000e+03,1.633530e-04,2.302585,0.0,0.0,15.018054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
381033,2412.65,9056421.0,2413.4,2720.0,0.0,0.0,0.0,308.30,0.0,0.0,...,1.312754e+01,0.002659,4.222226e-02,9.347191e-07,2.930357e+07,2.054806e-01,5.731073,0.0,0.0,16.018985
381034,2412.65,9056421.0,2413.4,2740.0,0.0,0.0,0.0,324.15,0.0,0.0,...,9.525959e+00,0.002310,5.674432e-02,7.547991e-07,3.405949e+07,2.382107e-01,5.781206,0.0,0.0,16.018985
381035,2412.65,9056421.0,2413.4,2760.0,0.0,0.0,0.0,340.25,0.0,0.0,...,6.775493e+00,0.002028,7.242715e-02,6.014315e-07,3.939076e+07,2.691229e-01,5.829681,0.0,0.0,16.018985
381036,2412.65,9056421.0,2413.4,2780.0,0.0,0.0,0.0,356.65,0.0,0.0,...,4.725799e+00,0.001797,8.885430e-02,4.730159e-07,4.536560e+07,2.980844e-01,5.876755,0.0,0.0,16.018985
381037,2412.65,9056421.0,2413.4,2800.0,0.0,0.0,0.0,373.30,0.0,0.0,...,3.233717e+00,0.001606,1.056370e-01,3.673051e-07,5.202043e+07,3.250185e-01,5.922382,0.0,0.0,16.018985